<div class="form-group">
          <label for="no-phone">رقم الهاتف</label>
          <select id="no-phone">
                      <option value="-Choose-">-اختيار-</option>
                      <option value="994"> أذربيجان (994)</option>
                      <option value="374"> أرمينيا (374)</option>
                      <option value="297"> أروبا (297)</option>
                      <option value="61"> أستراليا (61)</option>
                      <option value="93"> أفغانستان (93)</option>
                      <option value="355"> ألبانيا (355)</option>
                      <option value="49"> ألمانيا (49)</option>
                      <option value="268"> أنتيغوا وبربودا (268)</option>
                      <option value="376"> أندورا (376)</option>
                      <option value="244"> أنغولا (244)</option>
                      <option value="264"> أنغيلا (264)</option>
                      <option value="998"> أوزبكستان (998)</option>
                      <option value="256"> أوغندا (256)</option>
                      <option value="380"> أوكرانيا (380)</option>
                      <option value="353"> أيرلندا (353)</option>
                      <option value="354"> أيسلندا (354)</option>
                      <option value="251"> إثيوبيا (251)</option>
                      <option value="291"> إريتريا (291)</option>
                      <option value="34"> إسبانيا (34)</option>
                      <option value="372"> إستونيا (372)</option>
                      <option value="503"> إلسلفادور (503)</option>
                      <option value="62"> إندونيسيا (62)</option>
                      <option value="98"> إيران (98)</option>
                      <option value="39"> إيطاليا (39)</option>
                      <option value="54"> الأرجنتين (54)</option>
                      <option value="962"> الأردن (962)</option>
                      <option value="598"> الأوروغواي (598)</option>
                      <option value="593"> الإكوادور (593)</option>
                      <option value="971"> الإمارات العربية المتحدة (971)</option>
                      <option value="92"> الباكستان (92)</option>
                      <option value="973"> البحرين (973)</option>
                      <option value="55"> البرازيل (55)</option>
                      <option value="351"> البرتغال (351)</option>
                      <option value="1-242"> البهاما (1-242)</option>
                      <option value="387"> البوسنة والهرسك (387)</option>
                      <option value="420"> التشيك (420)</option>
                      <option value="382"> الجبل الأسود (382)</option>
                      <option value="213"> الجزائر (213)</option>
                      <option value="1-284"> الجزر العذراء البريطانية (1-284)</option>
                      <option value="45"> الدانمارك (45)</option>
                      <option value="966"> السعودية (966)</option>
                      <option value="221"> السنغال (221)</option>
                      <option value="249"> السودان (249)</option>
                      <option value="46"> السويد (46)</option>
                      <option value="212"> الصحراء الغربية (212)</option>
                      <option value="252"> الصومال (252)</option>
                      <option value="86"> الصين (86)</option>
                      <option value="964"> العراق (964)</option>
                      <option value="241"> الغابون (241)</option>
                      <option value="63"> الفيليبين (63)</option>
                      <option value="672"> القارة القطبية الجنوبية (672)</option>
                      <option value="237"> الكاميرون (237)</option>
                      <option value="965"> الكويت (965)</option>
                      <option value="212"> المغرب (212)</option>
                      <option value="52"> المكسيك (52)</option>
                      <option value="44"> المملكة المتحدة (44)</option>
                      <option value="47"> النرويج (47)</option>
                      <option value="43"> النمسا (43)</option>
                      <option value="227"> النيجر (227)</option>
                      <option value="91"> الهند (91)</option>
                      <option value="1"> الولايات المتحدة (1)</option>
                      <option value="81"> اليابان (81)</option>
                      <option value="967"> اليمن (967)</option>
                      <option value="30"> اليونان (30)</option>
                      <option value="675"> بابوا غينيا الجديدة (675)</option>
                      <option value="595"> باراغواي (595)</option>
                      <option value="507"> باناما (507)</option>
                      <option value="267"> بتسوانا (267)</option>
                      <option value="1-246"> بربادوس (1-246)</option>
                      <option value="673"> بروناي دار السلام (673)</option>
                      <option value="32"> بلجيكا (32)</option>
                      <option value="359"> بلغاريا (359)</option>
                      <option value="501"> بليز (501)</option>
                      <option value="880"> بنغلاديش (880)</option>
                      <option value="229"> بنين (229)</option>
                      <option value="975"> بوتان (975)</option>
                      <option value="787"> بورتو ريكو (787)</option>
                      <option value="226"> بوركينا فاسو (226)</option>
                      <option value="95"> بورما (95)</option>
                      <option value="257"> بوروندي (257)</option>
                      <option value="48"> بولندا (48)</option>
                      <option value="591"> بوليفيا (591)</option>
                      <option value="51"> بيرو (51)</option>
                      <option value="375"> بيلاروسيا (375)</option>
                      <option value="66"> تايلاند (66)</option>
                      <option value="886"> تايوان (886)</option>
                      <option value="993"> تركمانستان (993)</option>
                      <option value="90"> تركيا (90)</option>
                      <option value="868"> ترينيداد وتوباغو (868)</option>
                      <option value="235"> تشاد (235)</option>
                      <option value="56"> تشيلي (56)</option>
                      <option value="255"> تنزانيا (255)</option>
                      <option value="228"> توغو (228)</option>
                      <option value="676"> تونجا (676)</option>
                      <option value="216"> تونس (216)</option>
                      <option value="670"> تيمور الشرقية (670)</option>
                      <option value="876*"> جامايكا (876*)</option>
                      <option value="350"> جبل طارق (350)</option>
                      <option value="1-473"> جرينادا (1-473)</option>
                      <option value="299"> جرينلاند (299)</option>
                      <option value="599"> جزر الأنتيل الهولندية (599)</option>
                      <option value="269"> جزر القمر (269)</option>
                      <option value="1-441"> جزر برمودا (1-441)</option>
                      <option value="677"> جزر سليمان (677)</option>
                      <option value="298"> جزر فارو (298)</option>
                      <option value="1-345"> جزر كايمان (1-345)</option>
                      <option value="692"> جزر مارشال (692)</option>
                      <option value="247"> جزيرة الصعود (247)</option>
                      <option value="236"> جمهورية أفريقيا الوسطى (236)</option>
                      <option value="809"> جمهورية الدومنيكان (809)</option>
                      <option value="27"> جنوب أفريقيا (27)</option>
                      <option value="995"> جورجيا (995)</option>
                      <option value="253"> جيبوتي (253)</option>
                      <option value="1-767"> دومينيكا (1-767)</option>
                      <option value="250"> رواندا (250)</option>
                      <option value="7"> روسيا (7)</option>
                      <option value="40"> رومانيا (40)</option>
                      <option value="260"> زامبيا (260)</option>
                      <option value="263"> زيمبابوي (263)</option>
                      <option value="225"> ساحل العاج (225)</option>
                      <option value="684"> ساموا الأمريكية (684)</option>
                      <option value="378"> سان مارينو (378)</option>
                      <option value="784"> سانت فنسنت وجزر غرينادين (784)</option>
                      <option value="869"> سانت كيتس ونيفيس (869)</option>
                      <option value="94"> سريلانكا (94)</option>
                      <option value="968"> سلطنة عمان (968)</option>
                      <option value="421"> سلوفاكيا (421)</option>
                      <option value="386"> سلوفانيا (386)</option>
                      <option value="65"> سنغافورة (65)</option>
                      <option value="268"> سوازيلند (268)</option>
                      <option value="963"> سوريا (963)</option>
                      <option value="597"> سورينام (597)</option>
                      <option value="41"> سويسرا (41)</option>
                      <option value="232"> سيراليون (232)</option>
                      <option value="248"> سيشيل (248)</option>
                      <option value="381"> صربيا (381)</option>
                      <option value="992"> طاجيكستان (992)</option>
                      <option value="220"> غامبيا (220)</option>
                      <option value="233"> غانا (233)</option>
                      <option value="502"> غواتيمالا (502)</option>
                      <option value="590"> غواديلوب (590)</option>
                      <option value="592"> غويانا (592)</option>
                      <option value="224"> غينيا (224)</option>
                      <option value="240"> غينيا الاستوائية (240)</option>
                      <option value="245"> غينيا بيساو (245)</option>
                      <option value="33"> فرنسا (33)</option>
                      <option value="972"> فلسطين (972)</option>
                      <option value="58"> فنزويلا (58)</option>
                      <option value="358"> فنلندا (358)</option>
                      <option value="84"> فيتنام (84)</option>
                      <option value="679"> فيجي (679)</option>
                      <option value="357"> قبرص (357)</option>
                      <option value="996"> قرغيزستان (996)</option>
                      <option value="974"> قطر (974)</option>
                      <option value="7"> كازاخستان (7)</option>
                      <option value="385"> كرواتيا (385)</option>
                      <option value="855"> كمبوديا (855)</option>
                      <option value="1"> كندا (1)</option>
                      <option value="53"> كوبا (53)</option>
                      <option value="82"> كوريا الجنوبية (82)</option>
                      <option value="506"> كوستاريكا (506)</option>
                      <option value="57"> كولومبيا (57)</option>
                      <option value="242"> كونغو (242)</option>
                      <option value="254"> كينيا (254)</option>
                      <option value="371"> لاتفيا (371)</option>
                      <option value="856"> لاوس (856)</option>
                      <option value="961"> لبنان (961)</option>
                      <option value="370"> لتوانيا (370)</option>
                      <option value="352"> لوكسمبورغ (352)</option>
                      <option value="218"> ليبيا (218)</option>
                      <option value="231"> ليبيريا (231)</option>
                      <option value="423"> ليختنشتاين (423)</option>
                      <option value="266"> ليسوتو (266)</option>
                      <option value="853"> ماكاو (853)</option>
                      <option value="356"> مالطة (356)</option>
                      <option value="223"> مالي (223)</option>
                      <option value="60"> ماليزيا (60)</option>
                      <option value="261"> مدغشقر (261)</option>
                      <option value="20"> مصر (20)</option>
                      <option value="389"> مقدونيا (389)</option>
                      <option value="265"> ملاوي (265)</option>
                      <option value="960"> ملديف (960)</option>
                      <option value="976"> منغوليا (976)</option>
                      <option value="222"> موريتانيا (222)</option>
                      <option value="230"> موريشيوس (230)</option>
                      <option value="258"> موزمبيق (258)</option>
                      <option value="373"> مولدافيا (373)</option>
                      <option value="377"> موناكو (377)</option>
                      <option value="664"> مونتسيرات (664)</option>
                      <option value="691"> ميكرونيسيا (691)</option>
                      <option value="264"> ناميبيا (264)</option>
                      <option value="977"> نيبال (977)</option>
                      <option value="234"> نيجيريا (234)</option>
                      <option value="505"> نيكاراغوا (505)</option>
                      <option value="64"> نيوزيلاندا (64)</option>
                      <option value="509"> هايتي (509)</option>
                      <option value="504"> هندوراس (504)</option>
                      <option value="36"> هنغاريا (36)</option>
                      <option value="31"> هولندا (31)</option>
                      <option value="852"> هونغ كونغ (852)</option>
                      <option value="681"> واليس وفوتونا (681)</option>
                      <option value="381"> يوغسلافيا (381)</option>
        </select>
    </div>
